---
title: Scribble
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: A jekyll theme. Because I scribble.
url: 
signoff: 
disqus_shortname: 
facebook_appid: 
google_analytics: 
links:
- name: About
  url: "/about"
- name: Blog
  url: http://muan.co
  external: true
- name: GitHub
  url: http://github.com/muan
  external: true
highlighter: pygments
permalink: pretty
markdown: redcarpet
redcarpet:
  extensions:
  - smart
